package com.example.moliyafinance

object Variables {
    val jenis_transaksi = listOf(
        "Pemasukan",
        "Pengeluaran",
        "Hutang",
        "Piutang",
        "Tanam Modal",
        "Tarik Modal",
        "Transfer Uang"
    )

    data class DataAkun(
        val nomor: String,
        val nama: String,
        val kategori: String,
        val jenis: String
    )

    val akunList = listOf(
        DataAkun("1-10001", "Kas", "Kas & Bank", "Debit"),
        DataAkun("1-10002", "Rekening Bank", "Kas & Bank", "Debit"),
        DataAkun("1-10003", "Bank Mandiri", "Kas & Bank", "Debit"),
        DataAkun("1-10004", "Bank Negara Indonesia (BNI)", "Kas & Bank", "Debit"),
        DataAkun("1-10005", "Bank Rakyat Indonesia (BRI)", "Kas & Bank", "Debit"),
        DataAkun("1-10006", "Bank Tabungan Negara (BTN)", "Kas & Bank", "Debit"),
        DataAkun("1-10007", "Bank Central Asia (BCA)", "Kas & Bank", "Debit"),
        DataAkun("1-10008", "GoPay", "Kas & Bank", "Debit"),
        DataAkun("1-10009", "OVO", "Kas & Bank", "Debit"),
        DataAkun("1-10010", "Dana", "Kas & Bank", "Debit"),
        DataAkun("1-10011", "Link Aja", "Kas & Bank", "Debit"),
        DataAkun("1-10012", "Cashlez", "Kas & Bank", "Debit"),
        DataAkun("1-10100", "Piutang Usaha", "Akun Piutang", "Debit"),
        DataAkun("1-10101", "Piutang Belum Ditagih", "Akun Piutang", "Debit"),
        DataAkun("1-10200", "Persediaan Barang", "Persediaan", "Debit"),
        DataAkun("1-10300", "Piutang Lainnya", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10301", "Piutang Karyawan", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10400", "Dana Belum Disetor", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10401", "Aset Lancar Lainnya", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10402", "Biaya Dibayar Di Muka", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10403", "Uang Muka", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10500", "PPN Masukan", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10501", "Pajak Penghasilan Dibayar Di Muka - PPh 22", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10502", "Pajak Penghasilan Dibayar Di Muka - PPh 23", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10503", "Pajak Penghasilan Dibayar Di Muka - PPh 25", "Harta Lancar Lainnya", "Debit"),
        DataAkun("1-10700", "Aktiva Tetap - Tanah", "Harta Tetap", "Debit"),
        DataAkun("1-10701", "Aset Tetap - Bangunan", "Harta Tetap", "Debit"),
        DataAkun("1-10702", "Aset Tetap - Pengembangan Bangunan", "Harta Tetap", "Debit"),
        DataAkun("1-10703", "Aset Tetap - Kendaraan", "Harta Tetap", "Debit"),
        DataAkun("1-10704", "Aset Tetap - Mesin & Peralatan", "Harta Tetap", "Debit"),
        DataAkun("1-10705", "Aset Tetap - Peralatan Kantor", "Harta Tetap", "Debit"),
        DataAkun("1-10706", "Aset Tetap - Aset Sewaan", "Harta Tetap", "Debit"),
        DataAkun("1-10707", "Aset Tidak Berwujud", "Harta Tetap", "Debit"),
        DataAkun("1-10751", "Akumulasi Penyusutan - Bangunan", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10752", "Akumulasi Penyusutan - Pengembangan Bangunan", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10753", "Akumulasi Penyusutan - Kendaraan", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10754", "Akumulasi Penyusutan - Mesin & Peralatan", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10755", "Akumulasi Penyusutan - Peralatan Kantor", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10756", "Akumulasi Penyusutan - Aset Sewaan", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10757", "Akumulasi Armotisasi", "Depresiasi & Armotisasi", "Kredit"),
        DataAkun("1-10800", "Investasi", "Harta Lainnya", "Debit"),
        DataAkun("2-20100", "Hutang Usaha", "Akun Hutang", "Kredit"),
        DataAkun("2-20101", "Hutang Belum Ditagih", "Akun Hutang", "Debit"),
        DataAkun("2-20200", "Hutang Lainnya", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20201", "Hutang Gaji", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20202", "Hutang Deviden", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20203", "Pendapatan Diterima Di Muka", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20301", "Sarana Kantor Terhutang", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20302", "Bunga Terhutang", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20399", "Biaya Terhutang lainnya", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20400", "Hutang Bank", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20500", "PPN Keluaran", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20501", "Hutang Pajak - PPh 21", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20502", "Hutang Pajak - PPh 22", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20503", "Hutang Pajak - PPh 23", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20504", "Hutang Pajak - PPh 29", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20599", "Hutang Pajak Lainnya", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20600", "Hutang Dari Pemegang Saham", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20601", "Kewajiban Lancar Lainnya", "Kewajiban Lancar Lainnya", "Kredit"),
        DataAkun("2-20700", "Kewajiban Manfaat Karyawan", "Kewajiban Jangka Panjang", "Kredit"),
        DataAkun("3-30000", "Modal Saham", "Modal", "Kredit"),
        DataAkun("3-30001", "Modal Tambahan", "Modal", "Kredit"),
        DataAkun("3-30100", "Laba Ditahan", "Modal", "Kredit"),
        DataAkun("3-30200", "Deviden", "Modal", "Kredit"),
        DataAkun("3-30300", "Pendapatan Komprehensif Lainnya", "Modal", "Kredit"),
        DataAkun("3-30999", "Saldo Awal", "Modal", "Kredit"),
        DataAkun("4-40000", "Pendapatan", "Pendapatan", "Kredit"),
        DataAkun("4-40100", "Diskon Penjualan", "Pendapatan", "Kredit"),
        DataAkun("4-40200", "Pengembalian Penjualan", "Pendapatan", "Kredit"),
        DataAkun("5-50000", "Beban Pokok Pendapatan", "Harga Pokok Penjualan", "Debit"),
        DataAkun("5-50100", "Diskon Pembelian", "Harga Pokok Penjualan", "Debit"),
        DataAkun("5-50200", "Pengembalian Pembelian", "Harga Pokok Penjualan", "Debit"),
        DataAkun("5-50300", "Pengiriman / Pengangkutan", "Harga Pokok Penjualan", "Debit"),
        DataAkun("5-50400", "Biaya Import", "Harga Pokok Penjualan", "Debit"),
        DataAkun("5-50500", "Biaya Produksi", "Harga Pokok Penjualan", "Debit"),
        DataAkun("6-60000", "Biaya Penjualan", "Beban", "Debit"),
        DataAkun("6-60001", "Iklan & Promosi", "Beban", "Debit"),
        DataAkun("6-60002", "Komisi & Fee", "Beban", "Debit"),
        DataAkun("6-60003", "Bensin - Toll - dan Parkir - Penjualan", "Beban", "Debit"),
        DataAkun("6-60004", "Perjalanan (Travelling) - Penjualan", "Beban", "Debit"),
        DataAkun("6-60005", "Komunikasi - Penjualan", "Beban", "Debit"),
        DataAkun("6-60006", "Pemasaran Lainnya", "Beban", "Debit"),
        DataAkun("6-60100", "Biaya Umum & Administratif", "Beban", "Debit"),
        DataAkun("6-60101", "Gaji", "Beban", "Debit"),
        DataAkun("6-60102", "Upah", "Beban", "Debit"),
        DataAkun("6-60103", "Konsumsi & Transport", "Beban", "Debit"),
        DataAkun("6-60104", "Lembur", "Beban", "Debit"),
        DataAkun("6-60105", "Kesehatan", "Beban", "Debit"),
        DataAkun("6-60106", "THR dan Bonus", "Beban", "Debit"),
        DataAkun("6-60107", "Jamsostek", "Beban", "Debit"),
        DataAkun("6-60108", "Insentif", "Beban", "Debit"),
        DataAkun("6-60109", "Pesangon", "Beban", "Debit"),
        DataAkun("6-60110", "Tunjangan Lainnya", "Beban", "Debit"),
        DataAkun("6-60200", "Donasi", "Beban", "Debit"),
        DataAkun("6-60201", "Hiburan", "Beban", "Debit"),
        DataAkun("6-60202", "Bensin - Toll - dan Parkir - Umum", "Beban", "Debit"),
        DataAkun("6-60203", "Perbaikan dan Perawatan", "Beban", "Debit"),
        DataAkun("6-60204", "Perjalanan (Travelling) - Umum", "Beban", "Debit"),
        DataAkun("6-60205", "Konsumsi", "Beban", "Debit"),
        DataAkun("6-60206", "Komunikasi - Umum", "Beban", "Debit"),
        DataAkun("6-60207", "Iuran & Berlangganan", "Beban", "Debit"),
        DataAkun("6-60208", "Asuransi", "Beban", "Debit"),
        DataAkun("6-60209", "Biaya Hukum & Professional", "Beban", "Debit"),
        DataAkun("6-60210", "Beban Tunjangan Karyawan", "Beban", "Debit"),
        DataAkun("6-60211", "Sarana Kantor", "Beban", "Debit"),
        DataAkun("6-60212", "Pelatihan & Pengembangan", "Beban", "Debit"),
        DataAkun("6-60213", "Beban Hutang Buruk", "Beban", "Debit"),
        DataAkun("6-60214", "Pajak & Lisensi", "Beban", "Debit"),
        DataAkun("6-60215", "Denda", "Beban", "Debit"),
        DataAkun("6-60216", "Pengeluaran Barang Rusak", "Beban", "Debit"),
        DataAkun("6-60300", "Beban Kantor", "Beban", "Debit"),
        DataAkun("6-60301", "ATK & Print", "Beban", "Debit"),
        DataAkun("6-60302", "Materai", "Beban", "Debit"),
        DataAkun("6-60303", "Keamanan & Kebersihan", "Beban", "Debit"),
        DataAkun("6-60304", "Persediaan Material", "Beban", "Debit"),
        DataAkun("6-60305", "Sub Kontraktor", "Beban", "Debit"),
        DataAkun("6-60400", "Beban Sewa - Bangunan", "Beban", "Debit"),
        DataAkun("6-60401", "Beban Sewa - Kendaraan", "Beban", "Debit"),
        DataAkun("6-60402", "Beban Sewa - Sewa Operasional", "Beban", "Debit"),
        DataAkun("6-60403", "Beban Sewa - Lainnya", "Beban", "Debit"),
        DataAkun("6-60500", "Depresiasi - Bangunan", "Beban", "Debit"),
        DataAkun("6-60501", "Depresiasi - Pengembangan Bangunan", "Beban", "Debit"),
        DataAkun("6-60502", "Depresiasi - Kendaraan", "Beban", "Debit"),
        DataAkun("6-60503", "Depresiasi - Mesin & Peralatan", "Beban", "Debit"),
        DataAkun("6-60504", "Depresiasi - Peralatan Kantor", "Beban", "Debit"),
        DataAkun("6-60599", "Depresiasi - Aset Sewaan", "Beban", "Debit"),
        DataAkun("7-70000", "Pendapatan Bunga - Bank", "Pendapatan Lainnya", "Kredit"),
        DataAkun("7-70001", "Pendapatan Bunga - Waktu Deposit", "Pendapatan Lainnya", "Kredit"),
        DataAkun("7-70099", "Pendapatan Lainnya", "Pendapatan Lainnya", "Kredit"),
        DataAkun("8-80000", "Beban Bunga", "Beban Lainnya", "Debit"),
        DataAkun("8-80001", "Persediaan", "Beban Lainnya", "Debit"),
        DataAkun("8-80002", "(Keuntungan) / Kerugian Pembuangan Aset Tetap", "Beban Lainnya", "Debit"),
        DataAkun("8-80100", "Penyesuaian Persediaan", "Beban Lainnya", "Debit"),
        DataAkun("8-80999", "Biaya Lainnya", "Beban Lainnya", "Debit"),
        DataAkun("9-90000", "Pajak Penghasilan - Saat Ini", "Beban Lainnya", "Debit"),
        DataAkun("9-90001", "Pajak Penghasilan - Ditangguhkan", "Beban Lainnya", "Debit")
    )

}